// react/day03/course/md/App.js
import React from "react";
class App extends React.Component{
	constructor(props){
		super(props);
	}
	render(){
		return (
			<div id="container">
				<header className = "header" id="header"></header>
				<div id="content">
					{this.props.children}
				</div>
				<footer className = "footer" id="footer"></footer>
			</div>
		)
	}
}
export default App;

// vue/day03/8.16 VUE 3/day03/pro/com/App.vue
<template>
	<div class="container">
		<header class="header">头部</header>
		<div id="content">
			<router-view></router-view>
			
		</div>
		<footer class="footer">
			<v-footer></v-footer>
		</footer>
	</div>
</template>

<script>
	import MainFooter from "./MainFooter.vue";
	export default {
		data(){
			return {
				
			}
		},
		methods:{
			
		},
		components:{
			"v-footer":MainFooter
		}
		
	}
</script>
