// vue/8.18 VUEx 5/课件/day05/pro/com/MainFooter.vue
<template>
	<ul>
		<li ><router-link to="/home">首页</router-link></li>
		<li ><router-link to="/kind">分类</router-link></li>
		<li ><router-link to="/cart">购物车</router-link></li>
		<li ><router-link to="/user">我的</router-link></li>
		<li ><router-link to="/more">更多</router-link></li>
	</ul>
</template>

<script>
	export default {
		data(){
			return {
				
			}
		},
		methods:{
			
		}
	}
</script>

<style scoped>
	.router-link-exact-active.router-link-active{
		color:#f66;
	}
</style>

// react/day03/course/md/MainFooter.js

import React from "react";
import ReactDOM from "react-dom";
import HomeContent from "./HomeContent.js";
import KindContent from "./KindContent.js";
import CartContent from "./CartContent.js";
import UserContent from "./UserContent.js";
import MoreContent from "./MoreContent.js";

import {Link} from "react-router";

class MainFooter extends React.Component{
	constructor(props){
		super(props);
		this.state = {
			currentIndex:"0"
		}
	}
	
	render(){
		return (
			<ul>
				<li  ><a href="#/home">首页</a></li>
				<li  ><a href="#/kind">分类</a></li>
				<li  ><a href="#/cart">购物车</a></li>
				<li  ><a href="#/user">我的</a></li>
				<li  ><a href="#/more">更多</a></li>
			</ul>
		)
	}
}

export default MainFooter;
