// vue/day03/8.16 VUE 3/day03/mogu/md/App.vue


<template>
  <div class="container">
    <header class="header">头部 </header>
    <div id="content" >
       
        <router-view></router-view>
    </div>
    <footer class="footer">
        <ul>
            <li><router-link to="/home">首页</router-link></li>
            <li><router-link to="/kind">分类</router-link></li>
            <li><router-link to="/cart">购物车</router-link></li>
            <li><router-link to="/user">个人中心</router-link></li>
            <li><router-link to="/more">更多</router-link></li>
        </ul>
    </footer>
  </div>
</template>

<script>
    export default{
        data(){
            return{

            }
        }
    }
</script>

<style scoped>
    .router-link-exact-active.router-link-active{
        color:#f66;
    }
</style>

// react/day03/课件/course/md/App.js
import React from "react";
import {Link,IndexLink } from "react-router";
var ACTIVE = {
	color:"#f66"
}


class App extends React.Component{
	constructor(props){
		super(props);
	}
	render(){
		return (
			<div id="container">
				<header className = "header" id="header">
					{this.props.header}
				</header>
				<div id="content">
					{/*this.props.children*/}
					{this.props.content}
				</div>
				<footer className = "footer" id="footer">
					{this.props.footer}
				</footer>
			</div>
		)
	}
}
export default App;
