// react/7.31 React day1/课件/day01/course/pro/md/MainFooter.jsx

var React = require("react");

var MainFooter = React.createClass({
	getInitialState(){
		return {
			currentIndex : 0
		}
	},
	changeIndex:function(event){
		console.log(event.target.getAttribute("data-index"));
		var dataIndex = event.target.getAttribute("data-index");
		this.setState({
			currentIndex:dataIndex
		})
		//改变头部和内容区域
	},
	render:function(){
		return (
			<ul>
				<li className={this.state.currentIndex=='0'?'active':''} data-index="0" onClick = {this.changeIndex}>首页</li>
				<li className={this.state.currentIndex=='1'?'active':''} data-index="1" onClick = {this.changeIndex}>分类</li>
				<li className={this.state.currentIndex=='2'?'active':''} data-index="2" onClick = {this.changeIndex}>购物车</li>
				<li className={this.state.currentIndex=='3'?'active':''} data-index="3" onClick = {this.changeIndex}>我的</li>
				<li className={this.state.currentIndex=='4'?'active':''} data-index="4" onClick = {this.changeIndex}>更多</li>
			</ul>
		)
	}
})

module.exports = MainFooter;

// vue/day03/8.16 VUE 3/day03/course/com/MainFooter.vue
<template>
	<ul>
		<li :class="activeIndex == 0 ? 'active' : ''" @click = "changeIndex(0)">首页</li>
		<li :class="activeIndex == 1 ? 'active' : ''" @click = "changeIndex(1)">分类</li>
		<li :class="activeIndex == 2 ? 'active' : ''" @click = "changeIndex(2)">购物车</li>
		<li :class="activeIndex == 3 ? 'active' : ''" @click = "changeIndex(3)">我的</li>
		<li :class="activeIndex == 4 ? 'active' : ''" @click = "changeIndex(4)">更多</li>
	</ul>
</template>

<script>
	export default {
		data(){
			return {
				activeIndex:0
			}
		},
		methods:{
			changeIndex(index){
				console.log(index)
				this.activeIndex = index;
			}
		}
	}
</script>

<style>
</style>
