// vue/day03/8.16 VUE 3/day03/mogu/md/App.vue


<template>
  <div class="container">
    <header class="header">头部 </header>
    <div id="content" >
       
        <router-view></router-view>
    </div>
    <footer class="footer">
        <ul>
            <li><router-link to="/home">首页</router-link></li>
            <li><router-link to="/kind">分类</router-link></li>
            <li><router-link to="/cart">购物车</router-link></li>
            <li><router-link to="/user">个人中心</router-link></li>
            <li><router-link to="/more">更多</router-link></li>
        </ul>
    </footer>
  </div>
</template>

<script>
    export default{
        data(){
            return{

            }
        }
    }
</script>

<style scoped>
    .router-link-exact-active.router-link-active{
        color:#f66;
    }
</style>

// react/day03/下午/course/pro/md/App.js

import React from "react";
import {Link, IndexLink} from "react-router";

export default class App extends React.Component{
	constructor(props){
		super(props)
	}
	
	render(){
		
		return (
			<div id="container">
				{this.props.type}
				<footer id="footer">
					<ul>
						<li>
							<IndexLink to = "/" activeClassName="active">首页</IndexLink>
						</li>
						<li>
							<Link to = "/kind" activeClassName="active">分类</Link>
						</li>
						<li>
							<Link to = "/cart" activeClassName="active">购物车</Link>
						</li>
						<li>
							<Link to = "/user" activeClassName="active">我的</Link>
						</li>
						<li>
							<Link to = "/more" activeClassName="active">更多</Link>
						</li>
					</ul>
				</footer>
			</div>
		)
	}
}
