// vue/8.18 VUEx 5/课件/day05/pro/com/MainFooter.vue
<template>
	<ul>
		<li ><router-link to="/home">首页</router-link></li>
		<li ><router-link to="/kind">分类</router-link></li>
		<li ><router-link to="/cart">购物车</router-link></li>
		<li ><router-link to="/user">我的</router-link></li>
		<li ><router-link to="/more">更多</router-link></li>
	</ul>
</template>

<script>
	export default {
		data(){
			return {
				
			}
		},
		methods:{
			
		}
	}
</script>

<style scoped>
	.router-link-exact-active.router-link-active{
		color:#f66;
	}
</style>

// react/day03/下午/course/md/MainFooter.js

import React from "react";
import ReactDOM from "react-dom";

import {Link,IndexLink} from "react-router";

class MainFooter extends React.Component{
	constructor(props){
		super(props);
	}
	
	render(){
		return (
			<ul>
				<li  ><IndexLink to="/" activeClassName="active">首页</IndexLink></li>
				<li  ><Link to="/kind" activeClassName="active">分类</Link></li>
				<li  ><Link to="/cart" activeClassName="active">购物车</Link></li>
				<li  ><Link to="/user" activeClassName="active">我的</Link></li>
				<li  ><Link to="/more" activeClassName="active">更多</Link></li>
			</ul>
		)
	}
}

export default MainFooter;
